specfile_path: syft.spec

upstream_package_name: syft
upstream_project_url: https://github.com/anchore/syft
downstream_package_name: syft

upstream_tag_template: v{version}

# Dependencies needed to create the SRPM (vendor archive)
srpm_build_deps:
  - go-vendor-tools
  - golang
  - rpmdevtools

jobs:
# PHASE 1: COPR builds for testing
# Build in COPR on pull requests
- job: copr_build
  trigger: pull_request
  owner: rsturla
  project: packages
  targets:
    - fedora-rawhide-x86_64
    - fedora-rawhide-aarch64

# Build in COPR when new upstream release is tagged
- job: copr_build
  trigger: release
  owner: rsturla
  project: packages
  targets:
    - fedora-rawhide-x86_64
    - fedora-rawhide-aarch64
    - fedora-43-x86_64
    - fedora-43-aarch64
    - fedora-42-x86_64
    - fedora-42-aarch64

# PHASE 2: Official Fedora (enable when ready to submit)
# Creates PRs to Fedora dist-git when upstream releases
# - job: pull_from_upstream
#   trigger: release
#   dist_git_branches:
#     - rawhide

# Builds in Koji after dist-git PR is merged
# - job: koji_build
#   trigger: commit
#   dist_git_branches:
#     - rawhide

actions:
  # For COPR builds: create vendor archive from upstream source
  post-upstream-clone:
    # https://fedora.gitlab.io/sigs/go/go-vendor-tools/scenarios/#manual-update
    - bash -c 'wget https://github.com/anchore/syft/archive/v${PACKIT_PROJECT_VERSION}/syft-${PACKIT_PROJECT_VERSION}.tar.gz'
    - bash -c 'export GOTOOLCHAIN=auto && go_vendor_archive create --config go-vendor-tools.toml syft.spec'
    - bash -c 'go_vendor_license --config go-vendor-tools.toml --path syft.spec report --verify-spec || true'

  # For Fedora dist-git (Phase 2): runs after syncing to dist-git
  # post-modifications:
  #   - |
  #     sh -xeuc "
  #       cd $PACKIT_DOWNSTREAM_REPO
  #       export GOTOOLCHAIN=auto
  #       go_vendor_archive create --config go-vendor-tools.toml syft.spec
  #       go_vendor_license \
  #         --config go-vendor-tools.toml \
  #         --path syft.spec \
  #         report \
  #         --verify-spec
  #     "

create_sync_note: false
